language: python
python:
    - "3.5"
    - "3.4"
before_install:
    - git clone https://github.com/ONSdigital/sdx-common.git
    - pip3 install ./sdx-common
install:
- "pip install -r requirements.txt"
- "pip install -r test_requirements.txt"
script:
- flake8
- python -m unittest tests/*.py
